FROM python:3.12-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .


ENV PYTHONPATH=/app:$PYTHONPATH


EXPOSE 8001

CMD ["sh", "-c", "python scripts/init_db.py && uvicorn api.main:app --host 0.0.0.0 --port 8001"]
